expr_name: convnet2_mnist_cls
device: cuda
seed: 42

data:
  train:
    dataset: MNIST
    root: data/
    download: True
    mode: train
  val:
    dataset: MNIST
    root: data/
    download: True
    mode: val
  test:
    dataset: MNIST
    root: data/
    download: True
    mode: test

model:
  name: ConvNet2
  in_channels: 1
  layers: [8, 16, 32]
  class_num: 10

hyperparameters:
  batch_size: 32
  optim: AdamW
  lr: 0.0001
  loss_fn: cross-entropy
  epochs: 10

ckpt_path: logs/convnet2_mnist_cls